#
#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8
#      enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    sql-script-encoding: utf-8

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #update #create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

logging:
  level:
    com.example.log: debug


payment:
  iamport:
    apiKey: ${iamport.apiKey}
    secretKey: ${iamport.apiSecret}


jwt:
  secret: bFYyb3E5bGtZeUNsZUtoUFltc01PYVBmNE44eUh0U1h2cnIzdlVsdEJ1ZmxmVzBsTEE3N0dTTEpRMGFHUjhaRjRWWmhpNko2WkJEcGJycTAK
